// Generated by gencpp from file go_player/Player_orderRequest.msg
// DO NOT EDIT!


#ifndef GO_PLAYER_MESSAGE_PLAYER_ORDERREQUEST_H
#define GO_PLAYER_MESSAGE_PLAYER_ORDERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace go_player
{
template <class ContainerAllocator>
struct Player_orderRequest_
{
  typedef Player_orderRequest_<ContainerAllocator> Type;

  Player_orderRequest_()
    : state()
    , kind()
    , level()  {
    }
  Player_orderRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , kind(_alloc)
    , level(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _kind_type;
  _kind_type kind;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _level_type;
  _level_type level;





  typedef boost::shared_ptr< ::go_player::Player_orderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::go_player::Player_orderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Player_orderRequest_

typedef ::go_player::Player_orderRequest_<std::allocator<void> > Player_orderRequest;

typedef boost::shared_ptr< ::go_player::Player_orderRequest > Player_orderRequestPtr;
typedef boost::shared_ptr< ::go_player::Player_orderRequest const> Player_orderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::go_player::Player_orderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::go_player::Player_orderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace go_player

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'go_player': ['/home/mrobot/ros_chess_svm/src/go_player/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::go_player::Player_orderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::go_player::Player_orderRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::go_player::Player_orderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::go_player::Player_orderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::go_player::Player_orderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::go_player::Player_orderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::go_player::Player_orderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3c58b4f1576da4268c38a742885e2c3";
  }

  static const char* value(const ::go_player::Player_orderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3c58b4f1576da42ULL;
  static const uint64_t static_value2 = 0x68c38a742885e2c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::go_player::Player_orderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "go_player/Player_orderRequest";
  }

  static const char* value(const ::go_player::Player_orderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::go_player::Player_orderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string state\n\
string kind\n\
string level\n\
";
  }

  static const char* value(const ::go_player::Player_orderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::go_player::Player_orderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.kind);
      stream.next(m.level);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Player_orderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::go_player::Player_orderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::go_player::Player_orderRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
    s << indent << "kind: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.kind);
    s << indent << "level: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.level);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GO_PLAYER_MESSAGE_PLAYER_ORDERREQUEST_H
