// Generated by gencpp from file go_player/player_order.msg
// DO NOT EDIT!


#ifndef GO_PLAYER_MESSAGE_PLAYER_ORDER_H
#define GO_PLAYER_MESSAGE_PLAYER_ORDER_H

#include <ros/service_traits.h>


#include <go_player/player_orderRequest.h>
#include <go_player/player_orderResponse.h>


namespace go_player
{

struct player_order
{

typedef player_orderRequest Request;
typedef player_orderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct player_order
} // namespace go_player


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::go_player::player_order > {
  static const char* value()
  {
    return "1e0b8396f26d47b0b616e36d5b4d6a67";
  }

  static const char* value(const ::go_player::player_order&) { return value(); }
};

template<>
struct DataType< ::go_player::player_order > {
  static const char* value()
  {
    return "go_player/player_order";
  }

  static const char* value(const ::go_player::player_order&) { return value(); }
};


// service_traits::MD5Sum< ::go_player::player_orderRequest> should match 
// service_traits::MD5Sum< ::go_player::player_order > 
template<>
struct MD5Sum< ::go_player::player_orderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::go_player::player_order >::value();
  }
  static const char* value(const ::go_player::player_orderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::go_player::player_orderRequest> should match 
// service_traits::DataType< ::go_player::player_order > 
template<>
struct DataType< ::go_player::player_orderRequest>
{
  static const char* value()
  {
    return DataType< ::go_player::player_order >::value();
  }
  static const char* value(const ::go_player::player_orderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::go_player::player_orderResponse> should match 
// service_traits::MD5Sum< ::go_player::player_order > 
template<>
struct MD5Sum< ::go_player::player_orderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::go_player::player_order >::value();
  }
  static const char* value(const ::go_player::player_orderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::go_player::player_orderResponse> should match 
// service_traits::DataType< ::go_player::player_order > 
template<>
struct DataType< ::go_player::player_orderResponse>
{
  static const char* value()
  {
    return DataType< ::go_player::player_order >::value();
  }
  static const char* value(const ::go_player::player_orderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GO_PLAYER_MESSAGE_PLAYER_ORDER_H
